const burger = document.querySelector("svg[id = 'icoOpen']")
const contactIcon = document.querySelector("img[src = 'pictures/contact_icon.png'")
const contactTitle = document.querySelector("a[ href = './index.html']")
const searchZone = document.querySelector("input[name = 'search']")
const searchIcon = document.querySelector("img[src = 'pictures/searchIcon.jpg']")
const header = document.querySelector("header")
const btnCreateContact = document.querySelector("button[type = 'button']")


searchIcon.classList.add('alignDimine')
burger.classList.add('alignDimine')
contactIcon.classList.add('alignDimine')
contactTitle.classList.add('bigger')
searchZone.classList.add('goodLooking')
searchZone.setAttribute("placeHolder","Rechercher")
header.classList.add('centered')
btnCreateContact.classList.add('measureColor')
